### ISSUE TITLE
How to clear cache in Python instead of via CLI?

### ISSUE THREAD

**Issue by jonathanlaniado** [mattdodge/yahoofantasy#43]
Thanks for adding the functionality. I've tried doing something like this, which did not appear to work.

`yahoofantasy.util.persistence.clear(["auth"], ctx._persist_key)`

**Comment by mattdodge** [comment]
Ah yes, the `clear` method will only clear it in the saved file, not in memory. It probably should do both to be more consistent but in the meantime you can do something like this
```python
import yahoofantasy.util.persistence as persistence
persistence.clear(['auth'], ctx._persist_key)
persistence.CURRENT_PERSISTENCE.clear()
```
