### ISSUE TITLE
having issues with League.weeks()

### ISSUE THREAD

**Issue by mattdodge** [mattdodge/yahoofantasy#46]
### Discussed in https://github.com/mattdodge/yahoofantasy/discussions/45

<div type='discussions-op-text'>

<sup>Originally posted by **prestonlam53** November 14, 2022</sup>
hey everyone,

when I try to get league.weeks(), I get an error that says: 

  File "/Users/.../opt/anaconda3/envs/.../lib/python3.8/site-packages/yahoofantasy/resources/league.py", line 44, in weeks
    if not self.start_week or not self.end_week:
AttributeError: 'League' object has no attribute 'start_week'

Has anyone else faced this issue or knows why I'm getting an attribute error? I see in my league settings that there's a clear start and end date, and we go week 1 to week 21. Able to get other attributes about the league like standing data.
</div>

**Comment by JCacho2007** [comment]
Hi, I'm having the same issue when trying to query my fantasy baseball league. What was the resolution?
