### ISSUE TITLE
Matchups not working

### ISSUE THREAD

**Issue by chrisjameschamp** [mattdodge/yahoofantasy#55]
I keep trying to run this example for an old NFL Fantasy League.  

`week_3 = league.weeks()[2]
for matchup in week_3.matchups:
    print(f"{matchup.team1.name} vs {matchup.team2.name}")`

I keep getting the followering error:
`AttributeError: 'League' object has no attribute 'start_week'`

**Comment by mattdodge** [comment]
How are you getting the `league` object? Can you post your full code snippet please?

**Comment by chrisjameschamp** [comment]
I have no idea, I think I was doing it wrong, I have gotten it to work by just trial and error
