### ISSUE TITLE
Unable to get a weekly matchup data

### ISSUE THREAD

**Issue by ivthoughts** [mattdodge/yahoofantasy#56]
I was reviewing and using the concept code you listed. However, when I got to the code for weekly matchups.
The error is there is no start_week variable for the week object.

For context, I am exploring a 2023 MLB H2H categories league.
FYI, I am using Syder and below is the error I received: 

**week_3 = league.weeks()[2]**
Traceback (most recent call last):

  Cell In[5], line 1
    week_3 = league.weeks()[2]

  File ~\Anaconda3\Lib\site-packages\yahoofantasy\resources\league.py:44 in weeks
    if not self.start_week or not self.end_week:

AttributeError: 'League' object has no attribute 'start_week'

**Comment by mattdodge** [comment]
Ah yep that's a bug - I'll get that doc updated. In the meantime, get the league from `ctx.get_leagues` - something like this should do it:
```python
leagues = ctx.get_leagues('mlb', 2023)
league = next(lg for lg in leagues if lg.id == '422.l.17549')
```

**Comment by ivthoughts** [comment]
Thank you! Just wanted to confirm, this did the trick!

BTW, is this just for H2H leagues or does this work for roto leagues as well?

**Comment by mattdodge** [comment]
Great! Will get the docs updated and fix the code to raise a more useful exception.

The code to get the league will be the same for H2H or roto, but the concept of weeks (i.e., `league.weeks()`) only exists for H2H
