### ISSUE TITLE
NBA support? 

### ISSUE THREAD

**Issue by WhosNickDoglio** [mattdodge/yahoofantasy#6]
Was excited when I found this and then immediately got a "nba is not a valid game, must be 'mlb' or 'nfl"  error 🙃

Is there anything blocking NBA support? 

Looking through the code I _think_ I just need to add the nba codes to [this file](https://github.com/mattdodge/yahoofantasy/blob/master/yahoofantasy/api/games.py)

Would you be open to a PR?

**Comment by mattdodge** [comment]
Absolutely open to a PR! And yeah I think you're probably right that it will mostly work. Some of the stats and game codes will need to be updated but the overall API access will still be there
