### ISSUE TITLE
Get player projected points?

### ISSUE THREAD

**Issue by nsfy33** [mattdodge/yahoofantasy#66]
Thanks for the fantastic package. 

I was wondering if it is possible to get projected points for a given player in a given week. I looked through the result you get from a call to player stats endpoint and it didn't seem to be there. But maybe it is in a different location?

If you know it is/isn't possible and, if so, how I could try a PR or at least use some custom code myself.

The reason is I want to look retroactively at the season and projected points are helpful for understanding what we knew then (also including things like injuries, as they would be projected 0)

**Comment by mattdodge** [comment]
Unfortunately Yahoo doesn't expose their player projections via any API. A bit more discussion about it here https://github.com/mattdodge/yahoofantasy/discussions/34. Screen scraping is probably your best bet if you want to grab historical projections for your league I'm afraid, this library won't be able to help though
